server:
  error:
    include-message: always
    include-binding-errors: always
  port: 80

spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: leaguegang2023@gmail.com
    password: jandmwmjmhgwcazm

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    com.example.demo.Controllers.*: trace
    com.example.demo.login.*: trace


